revert old linting.yml

diff --git a/workflows/linting.yml b/workflows/linting.yml
--- a/workflows/linting.yml
+++ b/workflows/linting.yml
@@ -19,6 +19,28 @@ jobs:
         with:
           node-version: "20"
 
+      - name: Install dependencies
+        run: |
+          composer install
+          npm install
+          npm install @wordpress/scripts --save-dev
+
+      - name: Validate Composer configuration
+        run: |
+          OUTPUT=$(composer validate --no-check-publish)
+          if grep -q 'ERROR' <<< "$OUTPUT"; then
+            exit 1
+          fi
+
+      - name: Lint PHP
+        run: |
+          OUTPUT=$(composer phpcs-allow-todo --no-check-publish 2>&1)
+          echo "$OUTPUT" | tee phpcs_output.log
+          if grep -q 'ERROR' <<< "$OUTPUT"; then
+            echo "PHPCS found errors. Check phpcs_output.log for details."
+            exit 1
+          fi
+
       - name: Lint CSS
         run: |
           npm run lint:css
